<?php
session_start();
include '../includes/db.php';
include '../includes/functions.php';
include '../includes/mail.php'; 

if(!isset($_SESSION['agent_id'])){
    die("<p style='color:red;'>You must be logged in as an agent.</p>");
}

$agent_user_id = $_SESSION['user_id'] ?? null;

// Fetch agent info
$stmt = $conn->prepare("SELECT agent_id, branch FROM agents WHERE user_id=?");
$stmt->bind_param("i", $agent_user_id);
$stmt->execute();
$agent_data = $stmt->get_result()->fetch_assoc();

if(!$agent_data){
    die("<p style='color:red;'>Agent profile not found.</p>");
}

$agent_id = $agent_data['agent_id'];
$branch = $agent_data['branch'];

<<<<<<< HEAD
// Fetch all customers for dropdowns
$customers_result = $conn->query("SELECT customer_id, name, email FROM customers ORDER BY name");
=======
// Fetch existing admin-created couriers
$couriers_result = $conn->query("
    SELECT c.courier_id, c.tracking_number, s.name AS sender_name, r.name AS receiver_name
    FROM couriers c
    JOIN customers s ON c.sender_id = s.customer_id
    JOIN customers r ON c.receiver_id = r.customer_id
    WHERE c.agent_id IS NULL
    ORDER BY c.courier_id DESC
");
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)

$error = '';
$success = '';

<<<<<<< HEAD
if(isset($_POST['add'])){
    $sender_id     = intval($_POST['sender_id'] ?? 0);
    $receiver_id   = intval($_POST['receiver_id'] ?? 0);
    $from_location = $branch;
    $to_location   = trim($_POST['to_location'] ?? '');
    $courier_type  = trim($_POST['courier_type'] ?? '');
    $delivery_date = $_POST['delivery_date'] ?? '';
=======
if(isset($_POST['assign'])){
    $courier_id   = intval($_POST['courier_id']);
    $to_location  = trim($_POST['to_location']);
    $courier_type = trim($_POST['courier_type']);
    $delivery_date= $_POST['delivery_date'];
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)

    if(!$courier_id || !$to_location || !$courier_type || !$delivery_date){
        $error = "All fields are required.";
    } else {
<<<<<<< HEAD
        // **Fetch existing tracking number generated by admin**
        $stmt_track = $conn->prepare("
            SELECT courier_id, tracking_number 
            FROM couriers
            WHERE sender_id=? AND receiver_id=? AND agent_id=?
            ORDER BY courier_id DESC LIMIT 1
        ");
        $stmt_track->bind_param("iii", $sender_id, $receiver_id, $agent_id);
        $stmt_track->execute();
        $result_track = $stmt_track->get_result();

        if($result_track && $result_track->num_rows > 0){
            // Courier already exists → reuse tracking number
            $row = $result_track->fetch_assoc();
            $tracking_number = $row['tracking_number'];
            $courier_id = $row['courier_id'];
            $success = "Courier already exists. Tracking Number: $tracking_number";
        } else {
            // **No new tracking number is generated here** — agent cannot create a courier without admin
            $error = "Courier must be added by admin first before agent can update it.";
=======
        $stmt_update = $conn->prepare("
            UPDATE couriers SET agent_id=?, from_location=?, to_location=?, courier_type=?, delivery_date=? 
            WHERE courier_id=?
        ");
        $stmt_update->bind_param("issssi", $agent_id, $branch, $to_location, $courier_type, $delivery_date, $courier_id);

        if($stmt_update->execute()){
            $stmt_email = $conn->prepare("
                SELECT c.tracking_number, s.email AS sender_email, r.email AS receiver_email
                FROM couriers c
                JOIN customers s ON c.sender_id = s.customer_id
                JOIN customers r ON c.receiver_id = r.customer_id
                WHERE c.courier_id=?
            ");
            $stmt_email->bind_param("i", $courier_id);
            $stmt_email->execute();
            $courier_info = $stmt_email->get_result()->fetch_assoc();

            $subject = "Courier Assigned by Agent";
            $body = "
                <h3>Courier Assigned</h3>
                <p><b>Tracking Number:</b> {$courier_info['tracking_number']}</p>
                <p><b>From:</b> $branch</p>
                <p><b>To:</b> $to_location</p>
                <p><b>Courier Type:</b> $courier_type</p>
                <p><b>Delivery Date:</b> $delivery_date</p>
                <p>Status: booked</p>
            ";

            if(!empty($courier_info['sender_email'])) send_mail($courier_info['sender_email'], $subject, $body);
            if(!empty($courier_info['receiver_email'])) send_mail($courier_info['receiver_email'], $subject, $body);

            $success = "Courier assigned successfully! Tracking Number: {$courier_info['tracking_number']}";
        } else {
            $error = "Failed to assign courier. Please try again.";
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Assign Courier - Agent Panel</title>
<style>
*{margin:0;padding:0;box-sizing:border-box;font-family:'Segoe UI',sans-serif;}
<<<<<<< HEAD
html, body {height:100%;margin:0;overflow:hidden;}
.scroll-wrapper {height:100%;overflow:auto;-ms-overflow-style:none;scrollbar-width:none;}
.scroll-wrapper::-webkit-scrollbar {display:none;}
body {background:url('../assets/agent-add-courier.jpg') center/cover no-repeat fixed;position:relative;}
body::after{content:'';position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.35);z-index:-1;}
.navbar{display:flex;justify-content:space-between;align-items:center;padding:15px 30px;}
.logo{font-size:1.5rem;font-weight:bold;background:linear-gradient(135deg,#ff7e5f,#feb47b);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}
.logout{text-decoration:none;padding:12px 25px;border-radius:10px;font-weight:bold;color:white;background:linear-gradient(135deg,#ff7e5f,#feb47b);}
.container{max-width:600px;margin:50px auto;background:#fff;padding:25px;border-radius:20px;box-shadow:0 10px 30px rgba(0,0,0,0.1);}
h2{text-align:center;margin-bottom:20px;color:#ff7e5f;}
label{display:block;margin:10px 0 5px;color:#333;font-weight:600;}
input, textarea{width:100%;padding:12px;border-radius:10px;border:1px solid #ccc;margin-bottom:15px;font-size:1rem;}
textarea{resize:none;}
button{padding:14px;border:none;border-radius:10px;cursor:pointer;background:linear-gradient(135deg,#ff7e5f,#feb47b);color:white;font-weight:bold;width:100%;margin-top:10px;transition:0.3s;}
button:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,0.25);}
p.success{color:#28a745;text-align:center;margin-bottom:15px;}
p.error{color:#dc3545;text-align:center;margin-bottom:15px;}
.custom-select{position:relative;width:100%;margin-bottom:15px;}
.select-selected{background:#fff;border:1px solid #ccc;border-radius:10px;padding:12px;cursor:pointer;}
.select-selected:after{content:"\25BC";float:right;margin-left:10px;}
.select-items{position:absolute;background:#fff;top:100%;left:0;right:0;border:1px solid #ccc;border-radius:10px;z-index:99;max-height:200px;overflow-y:auto;display:none;scrollbar-width:none;}
.select-items::-webkit-scrollbar{display:none;}
.select-items div{padding:10px;cursor:pointer;}
.select-items div:hover{background:linear-gradient(135deg,#ff7e5f,#feb47b);color:white;}
.custom-select:hover .select-items{display:block;}
@media(max-width:600px){.container{margin:50px 15px;padding:20px;}input,textarea,button{font-size:0.95rem;padding:10px;}}
=======

/* BODY & SCROLLBAR */
body{background:url('../assets/agent-add-courier.jpg') center/cover no-repeat fixed;position:relative;}
body::after{content:'';position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.35);z-index:-1;}
.scroll-wrapper{height:100vh;overflow:auto;-ms-overflow-style:none;scrollbar-width:none;}
.scroll-wrapper::-webkit-scrollbar{display:none;}

/* NAVBAR */
.navbar{display:flex;justify-content:space-between;align-items:center;padding:15px 30px;}
.logo{font-size:1.5rem;font-weight:bold;background:linear-gradient(135deg,#ff7e5f,#feb47b);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}
.logout{text-decoration:none;padding:12px 25px;border-radius:10px;font-weight:bold;color:white;background:linear-gradient(135deg,#ff7e5f,#feb47b);}

/* CONTAINER */
.container{max-width:600px;margin:50px auto;background:#fff;padding:25px;border-radius:20px;box-shadow:0 10px 30px rgba(0,0,0,0.1);}
h2{text-align:center;margin-bottom:20px;color:#ff7e5f;}
label{display:block;margin:10px 0 5px;color:#333;font-weight:600;}
input, button{width:100%;padding:12px;border-radius:10px;border:1px solid #ccc;margin-bottom:15px;font-size:1rem;}
button{cursor:pointer;background:linear-gradient(135deg,#ff7e5f,#feb47b);color:white;font-weight:bold;border:none;}
p.success{color:#28a745;text-align:center;margin-bottom:15px;}
p.error{color:#dc3545;text-align:center;margin-bottom:15px;}

/* Glow effect on focus */
input:focus, button:focus, .custom-dropdown-btn:focus {
    outline:none;
    border-color:#ff7e5f;
    box-shadow:0 0 8px #ff7e5f;
}

/* CUSTOM DROPDOWN */
.custom-dropdown{
    position:relative;
    margin-bottom:15px;
}
.custom-dropdown-btn{
    width:100%;
    padding:12px;
    border-radius:10px;
    border:1px solid #ccc;
    cursor:pointer;
    background:#fff;
    display:flex;
    justify-content:space-between;
    align-items:center;
}
.custom-dropdown-btn::after{content:"▼"; font-size:0.8rem; color:#333;}
.custom-dropdown-content{
    display:none;
    position:absolute;
    top:100%; left:0; width:100%;
    background:#fff;
    border-radius:10px;
    overflow:hidden;
    box-shadow:0 6px 20px rgba(0,0,0,0.25);
    z-index:10;
}
.custom-dropdown-content div{
    padding:12px;
    cursor:pointer;
    transition:0.3s;
}
.custom-dropdown-content div:hover{
    background: linear-gradient(135deg,#ff7e5f,#feb47b);
    color:white;
}

/* RESPONSIVE */
@media(max-width:600px){
    .container{margin:50px 15px;padding:20px;}
    input, button, .custom-dropdown-btn, .custom-dropdown-content div{font-size:0.95rem;padding:10px;}
}
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)
</style>
</head>
<body>
<div class="scroll-wrapper">

<div class="navbar">
<div class="logo">Courier Agent</div>
<a href="../logout.php" class="logout">Logout</a>
</div>

<div class="container">
<<<<<<< HEAD
<h2>Add / Update Courier</h2>
=======
<h2>Assign Courier</h2>
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)
<?php if($error) echo "<p class='error'>$error</p>"; ?>
<?php if($success) echo "<p class='success'>$success</p>"; ?>

<form method="POST">
<<<<<<< HEAD

<label>Sender:</label>
<div class="custom-select" id="sender-select">
<div class="select-selected">Select Sender</div>
<div class="select-items">
<?php if($customers_result){ $customers_result->data_seek(0);
while($row = $customers_result->fetch_assoc()): ?>
<div data-value="<?= $row['customer_id'] ?>"><?= htmlspecialchars($row['name']) ?></div>
<?php endwhile; } ?>
</div>
</div>
<input type="hidden" name="sender_id" id="sender_id">

<label>Receiver:</label>
<div class="custom-select" id="receiver-select">
<div class="select-selected">Select Receiver</div>
<div class="select-items">
<?php if($customers_result){ $customers_result->data_seek(0);
while($row = $customers_result->fetch_assoc()): ?>
<div data-value="<?= $row['customer_id'] ?>"><?= htmlspecialchars($row['name']) ?></div>
<?php endwhile; } ?>
</div>
</div>
<input type="hidden" name="receiver_id" id="receiver_id">

<label>From Branch:</label>
<input type="text" name="from_location" value="<?= htmlspecialchars($branch) ?>" readonly>
=======

    <label>Select Courier (Admin Created):</label>
    <div class="custom-dropdown" id="courier-dropdown">
        <div class="custom-dropdown-btn" tabindex="0">Select Courier</div>
        <div class="custom-dropdown-content">
            <?php if($couriers_result){
                $couriers_result->data_seek(0);
                while($c = $couriers_result->fetch_assoc()){
                    $text = "[{$c['tracking_number']}] {$c['sender_name']} → {$c['receiver_name']}";
                    echo "<div data-value='{$c['courier_id']}'>$text</div>";
                }
            } ?>
        </div>
        <input type="hidden" name="courier_id" required>
    </div>

    <label>Destination (To):</label>
    <input type="text" name="to_location" required>
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)

<label>Destination:</label>
<input type="text" name="to_location" required>

<label>Courier Type:</label>
<input type="text" name="courier_type" required>

<label>Delivery Date:</label>
<input type="date" name="delivery_date" required>

<button type="submit" name="add">Add / Update Courier</button>

<<<<<<< HEAD
</form>
</div>

</div>

<script>
document.querySelectorAll('#sender-select .select-items div').forEach(opt=>{
    opt.addEventListener('click',()=>{
        document.querySelector('#sender-select .select-selected').textContent=opt.textContent;
        document.getElementById('sender_id').value=opt.dataset.value;
    });
});

document.querySelectorAll('#receiver-select .select-items div').forEach(opt=>{
    opt.addEventListener('click',()=>{
        document.querySelector('#receiver-select .select-selected').textContent=opt.textContent;
        document.getElementById('receiver_id').value=opt.dataset.value;
=======
    <button type="submit" name="assign">Assign Courier</button>
</form>
</div>
</div>

<script>
// Custom dropdown JS
document.querySelectorAll('.custom-dropdown').forEach(dropdown => {
    const btn = dropdown.querySelector('.custom-dropdown-btn');
    const content = dropdown.querySelector('.custom-dropdown-content');
    const hiddenInput = dropdown.querySelector('input[type=hidden]');

    btn.addEventListener('click', () => {
        content.style.display = content.style.display === 'block' ? 'none' : 'block';
        btn.focus(); // show glow on click
    });

    content.querySelectorAll('div').forEach(item => {
        item.addEventListener('click', () => {
            hiddenInput.value = item.dataset.value;
            btn.textContent = item.textContent;
            content.style.display = 'none';
        });
    });

    document.addEventListener('click', (e) => {
        if(!dropdown.contains(e.target)) content.style.display = 'none';
>>>>>>> 1c21ee6 (Added agent approval system, SMS updates, dashboard improvements, new registration pages)
    });
});
</script>

</body>
</html>
